/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Application {
    'appName': string;
    'organisation': string;
    'database'?: object;
    'filesystem'?: object;
    'composeDefinition'?: object;
    'status'?: object;
    'deploymentInformation'?: object;
    'imageReference'?: object;
    'containerNames'?: Array<string>;
    'minCapacity'?: number;
    'maxCapacity'?: number;
    'desiredCount'?: object;
    'runningCount'?: object;
    'environments'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appName",
            "baseName": "appName",
            "type": "string"
        },
        {
            "name": "organisation",
            "baseName": "organisation",
            "type": "string"
        },
        {
            "name": "database",
            "baseName": "database",
            "type": "object"
        },
        {
            "name": "filesystem",
            "baseName": "filesystem",
            "type": "object"
        },
        {
            "name": "composeDefinition",
            "baseName": "composeDefinition",
            "type": "object"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "object"
        },
        {
            "name": "deploymentInformation",
            "baseName": "deploymentInformation",
            "type": "object"
        },
        {
            "name": "imageReference",
            "baseName": "imageReference",
            "type": "object"
        },
        {
            "name": "containerNames",
            "baseName": "containerNames",
            "type": "Array<string>"
        },
        {
            "name": "minCapacity",
            "baseName": "minCapacity",
            "type": "number"
        },
        {
            "name": "maxCapacity",
            "baseName": "maxCapacity",
            "type": "number"
        },
        {
            "name": "desiredCount",
            "baseName": "desiredCount",
            "type": "object"
        },
        {
            "name": "runningCount",
            "baseName": "runningCount",
            "type": "object"
        },
        {
            "name": "environments",
            "baseName": "environments",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return Application.attributeTypeMap;
    }
}

