/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Bfc82010fc344962814feda95595f25f200Response {
    'message'?: string;
    'translatedComposeDefinition'?: object;
    'translationWarnings'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "translatedComposeDefinition",
            "baseName": "translatedComposeDefinition",
            "type": "object"
        },
        {
            "name": "translationWarnings",
            "baseName": "translationWarnings",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Bfc82010fc344962814feda95595f25f200Response.attributeTypeMap;
    }
}

