/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Container } from './container';

export class Compose {
    'containers'?: Array<Container>;
    'architecture'?: string;
    'taskCpu'?: number;
    'taskMemory'?: number;
    'taskRoleArn'?: string;
    'minCapacity'?: number;
    'maxCapacity'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "containers",
            "baseName": "containers",
            "type": "Array<Container>"
        },
        {
            "name": "architecture",
            "baseName": "architecture",
            "type": "string"
        },
        {
            "name": "taskCpu",
            "baseName": "taskCpu",
            "type": "number"
        },
        {
            "name": "taskMemory",
            "baseName": "taskMemory",
            "type": "number"
        },
        {
            "name": "taskRoleArn",
            "baseName": "taskRoleArn",
            "type": "string"
        },
        {
            "name": "minCapacity",
            "baseName": "minCapacity",
            "type": "number"
        },
        {
            "name": "maxCapacity",
            "baseName": "maxCapacity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Compose.attributeTypeMap;
    }
}

