/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ContainerImageReference {
    /**
    * Specifies whether the image is internal (ECR) or external (e.g., Docker Hub)
    */
    'type': ContainerImageReference.TypeEnum;
    /**
    * The image identifier. For \'internal\' type, this is the image tag. For \'external\' type, this is the full image name.
    */
    'identifier': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ContainerImageReference.TypeEnum"
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ContainerImageReference.attributeTypeMap;
    }
}

export namespace ContainerImageReference {
    export enum TypeEnum {
        Internal = <any> 'internal',
        External = <any> 'external'
    }
}
