/**
 * QuantCDN Unified API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContainerEnvironmentInner } from './containerEnvironmentInner';
import { ContainerImageReference } from './containerImageReference';
import { ContainerMountPointsInner } from './containerMountPointsInner';

export class Container {
    'name': string;
    'imageReference': ContainerImageReference;
    'cpu'?: number;
    'memory'?: number;
    'memoryReservation'?: number;
    'exposedPorts'?: Array<number>;
    'mountPoints'?: Array<ContainerMountPointsInner>;
    'environment'?: Array<ContainerEnvironmentInner>;
    'command'?: Array<string>;
    'entryPoint'?: Array<string>;
    'essential'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "imageReference",
            "baseName": "imageReference",
            "type": "ContainerImageReference"
        },
        {
            "name": "cpu",
            "baseName": "cpu",
            "type": "number"
        },
        {
            "name": "memory",
            "baseName": "memory",
            "type": "number"
        },
        {
            "name": "memoryReservation",
            "baseName": "memoryReservation",
            "type": "number"
        },
        {
            "name": "exposedPorts",
            "baseName": "exposedPorts",
            "type": "Array<number>"
        },
        {
            "name": "mountPoints",
            "baseName": "mountPoints",
            "type": "Array<ContainerMountPointsInner>"
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "Array<ContainerEnvironmentInner>"
        },
        {
            "name": "command",
            "baseName": "command",
            "type": "Array<string>"
        },
        {
            "name": "entryPoint",
            "baseName": "entryPoint",
            "type": "Array<string>"
        },
        {
            "name": "essential",
            "baseName": "essential",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Container.attributeTypeMap;
    }
}

