/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ContainerDependsOnInner {
    /**
    * The name of the container this container depends on
    */
    'containerName': string;
    /**
    * The condition to wait for on the dependency
    */
    'condition'?: ContainerDependsOnInner.ConditionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "containerName",
            "baseName": "containerName",
            "type": "string"
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "ContainerDependsOnInner.ConditionEnum"
        }    ];

    static getAttributeTypeMap() {
        return ContainerDependsOnInner.attributeTypeMap;
    }
}

export namespace ContainerDependsOnInner {
    export enum ConditionEnum {
        Start = <any> 'START',
        Healthy = <any> 'HEALTHY',
        Complete = <any> 'COMPLETE',
        Success = <any> 'SUCCESS'
    }
}
