/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ContainerSecretsInner {
    /**
    * The environment variable name to be set in the container
    */
    'name': string;
    /**
    * The key of the secret in the environment\'s \'app-secrets\' store
    */
    'valueFrom': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "valueFrom",
            "baseName": "valueFrom",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ContainerSecretsInner.attributeTypeMap;
    }
}

