/**
 * QuantCDN Unified API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateBackupRequest {
    /**
    * Optional backup description
    */
    'description'?: string;
    /**
    * Optional retention period in days
    */
    'retentionDays'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "retentionDays",
            "baseName": "retentionDays",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateBackupRequest.attributeTypeMap;
    }
}

