/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Compose } from './compose';

export class CreateEnvironmentRequest {
    'envName': string;
    'minCapacity'?: number;
    'maxCapacity'?: number;
    'cloneConfigurationFrom'?: string;
    'composeDefinition': Compose;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "envName",
            "baseName": "envName",
            "type": "string"
        },
        {
            "name": "minCapacity",
            "baseName": "minCapacity",
            "type": "number"
        },
        {
            "name": "maxCapacity",
            "baseName": "maxCapacity",
            "type": "number"
        },
        {
            "name": "cloneConfigurationFrom",
            "baseName": "cloneConfigurationFrom",
            "type": "string"
        },
        {
            "name": "composeDefinition",
            "baseName": "composeDefinition",
            "type": "Compose"
        }    ];

    static getAttributeTypeMap() {
        return CreateEnvironmentRequest.attributeTypeMap;
    }
}

