/**
 * QuantCDN Unified API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Cron } from './cron';
import { Volume } from './volume';

export class Environment {
    'envName': string;
    'status'?: string;
    'runningCount'?: number;
    'desiredCount'?: number;
    'minCapacity'?: number;
    'maxCapacity'?: number;
    'cloneConfigurationFrom'?: string;
    /**
    * Image tag suffix for cloning
    */
    'imageSuffix'?: string;
    'taskDefinition'?: object;
    'service'?: object;
    'loadBalancer'?: object;
    'securityGroup'?: object;
    'subnet'?: object;
    'vpc'?: object;
    'volumes'?: Array<Volume>;
    'cron'?: Array<Cron>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "envName",
            "baseName": "envName",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "runningCount",
            "baseName": "runningCount",
            "type": "number"
        },
        {
            "name": "desiredCount",
            "baseName": "desiredCount",
            "type": "number"
        },
        {
            "name": "minCapacity",
            "baseName": "minCapacity",
            "type": "number"
        },
        {
            "name": "maxCapacity",
            "baseName": "maxCapacity",
            "type": "number"
        },
        {
            "name": "cloneConfigurationFrom",
            "baseName": "cloneConfigurationFrom",
            "type": "string"
        },
        {
            "name": "imageSuffix",
            "baseName": "imageSuffix",
            "type": "string"
        },
        {
            "name": "taskDefinition",
            "baseName": "taskDefinition",
            "type": "object"
        },
        {
            "name": "service",
            "baseName": "service",
            "type": "object"
        },
        {
            "name": "loadBalancer",
            "baseName": "loadBalancer",
            "type": "object"
        },
        {
            "name": "securityGroup",
            "baseName": "securityGroup",
            "type": "object"
        },
        {
            "name": "subnet",
            "baseName": "subnet",
            "type": "object"
        },
        {
            "name": "vpc",
            "baseName": "vpc",
            "type": "object"
        },
        {
            "name": "volumes",
            "baseName": "volumes",
            "type": "Array<Volume>"
        },
        {
            "name": "cron",
            "baseName": "cron",
            "type": "Array<Cron>"
        }    ];

    static getAttributeTypeMap() {
        return Environment.attributeTypeMap;
    }
}

