/**
 * QuantCDN Unified API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetSshAccessCredentials200ResponseCredentials } from './getSshAccessCredentials200ResponseCredentials';

export class GetSshAccessCredentials200Response {
    'success'?: boolean;
    'credentials'?: GetSshAccessCredentials200ResponseCredentials;
    'clusterName'?: string;
    'taskArn'?: string;
    'taskId'?: string;
    'containerNames'?: Array<string>;
    'region'?: string;
    'expiresIn'?: number;
    'organizationScope'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "GetSshAccessCredentials200ResponseCredentials"
        },
        {
            "name": "clusterName",
            "baseName": "clusterName",
            "type": "string"
        },
        {
            "name": "taskArn",
            "baseName": "taskArn",
            "type": "string"
        },
        {
            "name": "taskId",
            "baseName": "taskId",
            "type": "string"
        },
        {
            "name": "containerNames",
            "baseName": "containerNames",
            "type": "Array<string>"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "expiresIn",
            "baseName": "expiresIn",
            "type": "number"
        },
        {
            "name": "organizationScope",
            "baseName": "organizationScope",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetSshAccessCredentials200Response.attributeTypeMap;
    }
}

