/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ScalingPolicy } from './scalingPolicy';

export class GetScalingPolicies200Response {
    'policies'?: Array<ScalingPolicy>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "policies",
            "baseName": "policies",
            "type": "Array<ScalingPolicy>"
        }    ];

    static getAttributeTypeMap() {
        return GetScalingPolicies200Response.attributeTypeMap;
    }
}

