/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Model06b225e9857930e3933804092dfa7a4aRequest {
    'action'?: string;
    'imageTag'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string"
        },
        {
            "name": "imageTag",
            "baseName": "imageTag",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Model06b225e9857930e3933804092dfa7a4aRequest.attributeTypeMap;
    }
}

