/**
 * QuantCDN Unified API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OrganizationsList200ResponseInner {
    /**
    * Organization name
    */
    'name'?: string;
    /**
    * Organization machine name
    */
    'machineName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "machineName",
            "baseName": "machine_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrganizationsList200ResponseInner.attributeTypeMap;
    }
}

