/**
 * QuantCDN Unified API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ScalingPolicy {
    'metric'?: ScalingPolicy.MetricEnum;
    'targetValue'?: number;
    'scaleInCooldownSeconds'?: number;
    'scaleOutCooldownSeconds'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "metric",
            "baseName": "metric",
            "type": "ScalingPolicy.MetricEnum"
        },
        {
            "name": "targetValue",
            "baseName": "targetValue",
            "type": "number"
        },
        {
            "name": "scaleInCooldownSeconds",
            "baseName": "scaleInCooldownSeconds",
            "type": "number"
        },
        {
            "name": "scaleOutCooldownSeconds",
            "baseName": "scaleOutCooldownSeconds",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ScalingPolicy.attributeTypeMap;
    }
}

export namespace ScalingPolicy {
    export enum MetricEnum {
        CpuUtilization = <any> 'CPUUtilization',
        MemoryUtilization = <any> 'MemoryUtilization',
        Rps = <any> 'RPS'
    }
}
