/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ScalingPolicy {
    'metric'?: string;
    'targetValue'?: number;
    'scaleInCooldownSeconds'?: number;
    'scaleOutCooldownSeconds'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "metric",
            "baseName": "metric",
            "type": "string"
        },
        {
            "name": "targetValue",
            "baseName": "targetValue",
            "type": "number"
        },
        {
            "name": "scaleInCooldownSeconds",
            "baseName": "scaleInCooldownSeconds",
            "type": "number"
        },
        {
            "name": "scaleOutCooldownSeconds",
            "baseName": "scaleOutCooldownSeconds",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ScalingPolicy.attributeTypeMap;
    }
}

