/**
 * QuantCDN Unified API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SyncOperation {
    'syncId'?: string;
    'syncType'?: string;
    'sourceEnvironment'?: string;
    'targetEnvironment'?: string;
    'status'?: string;
    'createdAt'?: string;
    'completedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "syncId",
            "baseName": "syncId",
            "type": "string"
        },
        {
            "name": "syncType",
            "baseName": "syncType",
            "type": "string"
        },
        {
            "name": "sourceEnvironment",
            "baseName": "sourceEnvironment",
            "type": "string"
        },
        {
            "name": "targetEnvironment",
            "baseName": "targetEnvironment",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SyncOperation.attributeTypeMap;
    }
}

