/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TestSearchExtractorsRequest {
    'url': string;
    'type': TestSearchExtractorsRequest.TypeEnum;
    'match': string;
    'extractors': Array<object>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TestSearchExtractorsRequest.TypeEnum"
        },
        {
            "name": "match",
            "baseName": "match",
            "type": "string"
        },
        {
            "name": "extractors",
            "baseName": "extractors",
            "type": "Array<object>"
        }    ];

    static getAttributeTypeMap() {
        return TestSearchExtractorsRequest.attributeTypeMap;
    }
}

export namespace TestSearchExtractorsRequest {
    export enum TypeEnum {
        Url = <any> 'url',
        ContentType = <any> 'content_type'
    }
}
