/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Compose } from './compose';

export class UpdateEnvironmentRequest {
    'composeDefinition': Compose;
    /**
    * Optional. Minimum number of tasks for auto-scaling. If provided at root level, will be merged into composeDefinition.
    */
    'minCapacity'?: number | null;
    /**
    * Optional. Maximum number of tasks for auto-scaling. If provided at root level, will be merged into composeDefinition.
    */
    'maxCapacity'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "composeDefinition",
            "baseName": "composeDefinition",
            "type": "Compose"
        },
        {
            "name": "minCapacity",
            "baseName": "minCapacity",
            "type": "number"
        },
        {
            "name": "maxCapacity",
            "baseName": "maxCapacity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UpdateEnvironmentRequest.attributeTypeMap;
    }
}

