/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V1Info } from './v1Info';
import { V1Transition } from './v1Transition';

export class V1ContentRequest {
    /**
    * The content URL. Must be relative and start with a leading \'/\'
    */
    'url': string;
    /**
    * The content (e.g. html)
    */
    'content': string;
    /**
    * If the asset should be published
    */
    'published': boolean;
    /**
    * User defined timestamp for this content item
    */
    'contentTimestamp'?: number;
    'info'?: V1Info;
    'transitions'?: Array<V1Transition>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "published",
            "baseName": "published",
            "type": "boolean"
        },
        {
            "name": "contentTimestamp",
            "baseName": "content_timestamp",
            "type": "number"
        },
        {
            "name": "info",
            "baseName": "info",
            "type": "V1Info"
        },
        {
            "name": "transitions",
            "baseName": "transitions",
            "type": "Array<V1Transition>"
        }    ];

    static getAttributeTypeMap() {
        return V1ContentRequest.attributeTypeMap;
    }
}

