/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V1Revision } from './v1Revision';

export class V1DeleteResponse {
    /**
    * Indicates at least one error occurred
    */
    'error'?: boolean;
    /**
    * List of any errors
    */
    'errors'?: Array<object>;
    'meta'?: Array<V1Revision>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "boolean"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<object>"
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "Array<V1Revision>"
        }    ];

    static getAttributeTypeMap() {
        return V1DeleteResponse.attributeTypeMap;
    }
}

