/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V1GetMetricSeriesResponseData } from './v1GetMetricSeriesResponseData';

export class V1GetMetricSeriesResponse {
    'success': boolean;
    'data': V1GetMetricSeriesResponseData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "V1GetMetricSeriesResponseData"
        }    ];

    static getAttributeTypeMap() {
        return V1GetMetricSeriesResponse.attributeTypeMap;
    }
}

