/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V1MetricDayStats } from './v1MetricDayStats';
import { V1MetricMinuteStats } from './v1MetricMinuteStats';
import { V1MetricMonthStats } from './v1MetricMonthStats';

export class V1GetMetricsResponseData {

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return V1GetMetricsResponseData.attributeTypeMap;
    }
}

