/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V1GlobalMetaResponseGlobalMeta } from './v1GlobalMetaResponseGlobalMeta';

export class V1GlobalMetaResponse {
    'globalMeta'?: V1GlobalMetaResponseGlobalMeta;
    'totalRecords'?: number;
    'totalPages'?: number;
    'page'?: number;
    'pageSize'?: number;
    'refineSearch'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "globalMeta",
            "baseName": "global_meta",
            "type": "V1GlobalMetaResponseGlobalMeta"
        },
        {
            "name": "totalRecords",
            "baseName": "total_records",
            "type": "number"
        },
        {
            "name": "totalPages",
            "baseName": "total_pages",
            "type": "number"
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number"
        },
        {
            "name": "pageSize",
            "baseName": "page_size",
            "type": "number"
        },
        {
            "name": "refineSearch",
            "baseName": "refine_search",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return V1GlobalMetaResponse.attributeTypeMap;
    }
}

