/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V1Info {
    'authorUser'?: string;
    'authorName'?: string;
    'authorEmail'?: string;
    'log'?: string;
    'custom1'?: string;
    'custom2'?: string;
    'source'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "authorUser",
            "baseName": "author_user",
            "type": "string"
        },
        {
            "name": "authorName",
            "baseName": "author_name",
            "type": "string"
        },
        {
            "name": "authorEmail",
            "baseName": "author_email",
            "type": "string"
        },
        {
            "name": "log",
            "baseName": "log",
            "type": "string"
        },
        {
            "name": "custom1",
            "baseName": "custom_1",
            "type": "string"
        },
        {
            "name": "custom2",
            "baseName": "custom_2",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1Info.attributeTypeMap;
    }
}

