/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V1MetricMonthStats {
    'total': number;
    'monthTotal': number;
    'monthSeries': { [key: string]: number; };
    'monthAverage': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "monthTotal",
            "baseName": "month_total",
            "type": "number"
        },
        {
            "name": "monthSeries",
            "baseName": "month_series",
            "type": "{ [key: string]: number; }"
        },
        {
            "name": "monthAverage",
            "baseName": "month_average",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return V1MetricMonthStats.attributeTypeMap;
    }
}

