/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V1RedirectItem } from './v1RedirectItem';

export class V1RedirectListResponse {
    'draw': number;
    'iTotalRecords': number;
    'iTotalDisplayRecords': number;
    'aaData': Array<V1RedirectItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "draw",
            "baseName": "draw",
            "type": "number"
        },
        {
            "name": "iTotalRecords",
            "baseName": "iTotalRecords",
            "type": "number"
        },
        {
            "name": "iTotalDisplayRecords",
            "baseName": "iTotalDisplayRecords",
            "type": "number"
        },
        {
            "name": "aaData",
            "baseName": "aaData",
            "type": "Array<V1RedirectItem>"
        }    ];

    static getAttributeTypeMap() {
        return V1RedirectListResponse.attributeTypeMap;
    }
}

