/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V1RedirectItem {
    /**
    * * @OA\\Schema(   schema=\"V1RedirectItem\",   type=\"object\",   required={\"url\",\"redirect_url\",\"redirect_http_code\",\"date_timestamp\",\"published\",\"revision_count\"},
    */
    'url': string;
    'redirectUrl': string;
    'redirectHttpCode': number;
    'dateTimestamp': string;
    'published': string;
    'revisionCount': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "redirectUrl",
            "baseName": "redirect_url",
            "type": "string"
        },
        {
            "name": "redirectHttpCode",
            "baseName": "redirect_http_code",
            "type": "number"
        },
        {
            "name": "dateTimestamp",
            "baseName": "date_timestamp",
            "type": "string"
        },
        {
            "name": "published",
            "baseName": "published",
            "type": "string"
        },
        {
            "name": "revisionCount",
            "baseName": "revision_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return V1RedirectItem.attributeTypeMap;
    }
}

