/**
 * QuantCDN API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V1Info } from './v1Info';
import { V1Transition } from './v1Transition';

export class V1Revision {
    'md5'?: string;
    'type'?: string;
    'byteLength'?: number;
    'revisionNumber'?: number;
    'dateTimestamp'?: number;
    'deleted'?: boolean;
    'deletedTimestamp'?: number;
    'transitions'?: Array<V1Transition>;
    'info'?: V1Info;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "md5",
            "baseName": "md5",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "byteLength",
            "baseName": "byte_length",
            "type": "number"
        },
        {
            "name": "revisionNumber",
            "baseName": "revision_number",
            "type": "number"
        },
        {
            "name": "dateTimestamp",
            "baseName": "date_timestamp",
            "type": "number"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "deletedTimestamp",
            "baseName": "deleted_timestamp",
            "type": "number"
        },
        {
            "name": "transitions",
            "baseName": "transitions",
            "type": "Array<V1Transition>"
        },
        {
            "name": "info",
            "baseName": "info",
            "type": "V1Info"
        }    ];

    static getAttributeTypeMap() {
        return V1Revision.attributeTypeMap;
    }
}

