/**
 * QuantCDN Unified API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V2Crawler {
    /**
    * Error message
    */
    'message': string;
    /**
    * Error flag
    */
    'error': boolean;
    /**
    * Crawler ID
    */
    'id': number;
    /**
    * Crawler name
    */
    'name'?: string;
    /**
    * Project ID
    */
    'projectId': number;
    /**
    * Crawler UUID
    */
    'uuid': string;
    /**
    * Crawler configuration (YAML)
    */
    'config': string;
    /**
    * Crawler domain
    */
    'domain': string;
    /**
    * Domain verification status
    */
    'domainVerified'?: number = 0;
    /**
    * URLs list (YAML)
    */
    'urlsList'?: string;
    /**
    * Creation timestamp
    */
    'createdAt'?: Date;
    /**
    * Last update timestamp
    */
    'updatedAt'?: Date;
    /**
    * Deletion timestamp
    */
    'deletedAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "projectId",
            "baseName": "project_id",
            "type": "number"
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "string"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "domainVerified",
            "baseName": "domain_verified",
            "type": "number"
        },
        {
            "name": "urlsList",
            "baseName": "urls_list",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "deletedAt",
            "baseName": "deleted_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return V2Crawler.attributeTypeMap;
    }
}

