/**
 * QuantCDN Unified API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V2CrawlerRequest {
    /**
    * Error message
    */
    'message': string;
    /**
    * Error flag
    */
    'error': boolean;
    /**
    * Crawler name
    */
    'name'?: string;
    /**
    * Domain to crawl
    */
    'domain': string;
    /**
    * Enable browser mode
    */
    'browserMode'?: boolean = false;
    /**
    * URLs to crawl
    */
    'urls'?: Array<string>;
    /**
    * Custom headers
    */
    'headers'?: { [key: string]: string; };
    /**
    * URLs to exclude
    */
    'exclude'?: Array<string>;
    /**
    * URLs to include
    */
    'include'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "browserMode",
            "baseName": "browser_mode",
            "type": "boolean"
        },
        {
            "name": "urls",
            "baseName": "urls",
            "type": "Array<string>"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "exclude",
            "baseName": "exclude",
            "type": "Array<string>"
        },
        {
            "name": "include",
            "baseName": "include",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return V2CrawlerRequest.attributeTypeMap;
    }
}

