/**
 * QuantCDN Unified API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V2ProjectRequest {
    /**
    * Error message
    */
    'message': string;
    /**
    * Error flag
    */
    'error': boolean;
    /**
    * Project name
    */
    'name': string;
    /**
    * Project machine name
    */
    'machineName': string;
    /**
    * Project region
    */
    'region'?: string;
    /**
    * Allow query parameters
    */
    'allowQueryParams'?: boolean;
    /**
    * Disable revisions
    */
    'disableRevisions'?: boolean;
    /**
    * Basic auth username
    */
    'basicAuthUsername'?: string;
    /**
    * Basic auth password
    */
    'basicAuthPassword'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "machineName",
            "baseName": "machine_name",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "allowQueryParams",
            "baseName": "allow_query_params",
            "type": "boolean"
        },
        {
            "name": "disableRevisions",
            "baseName": "disable_revisions",
            "type": "boolean"
        },
        {
            "name": "basicAuthUsername",
            "baseName": "basic_auth_username",
            "type": "string"
        },
        {
            "name": "basicAuthPassword",
            "baseName": "basic_auth_password",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V2ProjectRequest.attributeTypeMap;
    }
}

