/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ValidateComposeRequest {
    /**
    * The docker-compose.yml file content as a string
    */
    'compose': string;
    /**
    * Optional image tag suffix (query parameter takes precedence)
    */
    'imageSuffix'?: string;
    /**
    * Optional application name for context
    */
    'application'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "compose",
            "baseName": "compose",
            "type": "string"
        },
        {
            "name": "imageSuffix",
            "baseName": "imageSuffix",
            "type": "string"
        },
        {
            "name": "application",
            "baseName": "application",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ValidateComposeRequest.attributeTypeMap;
    }
}

