/**
 * QuantCDN Unified API
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Volume {
    'volumeId'?: string;
    'volumeName'?: string;
    'description'?: string;
    'environmentEfsId'?: string;
    'createdAt'?: string;
    'rootDirectory'?: string;
    'accessPointId'?: string;
    'accessPointArn'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "volumeId",
            "baseName": "volumeId",
            "type": "string"
        },
        {
            "name": "volumeName",
            "baseName": "volumeName",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "environmentEfsId",
            "baseName": "environmentEfsId",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "rootDirectory",
            "baseName": "rootDirectory",
            "type": "string"
        },
        {
            "name": "accessPointId",
            "baseName": "accessPointId",
            "type": "string"
        },
        {
            "name": "accessPointArn",
            "baseName": "accessPointArn",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Volume.attributeTypeMap;
    }
}

