/**
 * QuantCloud API
 * QuantCloud API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { D481164c455528711c302ff5e2b2bf5bRequest } from '../model/d481164c455528711c302ff5e2b2bf5bRequest';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'http://localhost';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum VariablesApiApiKeys {
}

export class VariablesApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: VariablesApiApiKeys, value: string) {
        (this.authentications as any)[VariablesApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * 
     * @summary Delete a variable
     * @param apiOrganisation The organisation ID
     * @param apiApplication The application ID
     * @param apiEnvironment The environment ID
     * @param apiVariable The variable key
     */
    public async _44955fb22628c96362249a89facbca92 (apiOrganisation: string, apiApplication: string, apiEnvironment: string, apiVariable: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/organisations/{api_organisation}/applications/{api_application}/environments/{api_environment}/variables/{api_variable}'
            .replace('{' + 'api_organisation' + '}', encodeURIComponent(String(apiOrganisation)))
            .replace('{' + 'api_application' + '}', encodeURIComponent(String(apiApplication)))
            .replace('{' + 'api_environment' + '}', encodeURIComponent(String(apiEnvironment)))
            .replace('{' + 'api_variable' + '}', encodeURIComponent(String(apiVariable)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'apiOrganisation' is not null or undefined
        if (apiOrganisation === null || apiOrganisation === undefined) {
            throw new Error('Required parameter apiOrganisation was null or undefined when calling _44955fb22628c96362249a89facbca92.');
        }

        // verify required parameter 'apiApplication' is not null or undefined
        if (apiApplication === null || apiApplication === undefined) {
            throw new Error('Required parameter apiApplication was null or undefined when calling _44955fb22628c96362249a89facbca92.');
        }

        // verify required parameter 'apiEnvironment' is not null or undefined
        if (apiEnvironment === null || apiEnvironment === undefined) {
            throw new Error('Required parameter apiEnvironment was null or undefined when calling _44955fb22628c96362249a89facbca92.');
        }

        // verify required parameter 'apiVariable' is not null or undefined
        if (apiVariable === null || apiVariable === undefined) {
            throw new Error('Required parameter apiVariable was null or undefined when calling _44955fb22628c96362249a89facbca92.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Get all variables for an environment
     * @param apiOrganisation The organisation ID
     * @param apiApplication The application ID
     * @param apiEnvironment The environment ID
     */
    public async _73fbde3b871d62621a0851e12ef3044c (apiOrganisation: string, apiApplication: string, apiEnvironment: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/organisations/{api_organisation}/applications/{api_application}/environments/{api_environment}/variables'
            .replace('{' + 'api_organisation' + '}', encodeURIComponent(String(apiOrganisation)))
            .replace('{' + 'api_application' + '}', encodeURIComponent(String(apiApplication)))
            .replace('{' + 'api_environment' + '}', encodeURIComponent(String(apiEnvironment)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'apiOrganisation' is not null or undefined
        if (apiOrganisation === null || apiOrganisation === undefined) {
            throw new Error('Required parameter apiOrganisation was null or undefined when calling _73fbde3b871d62621a0851e12ef3044c.');
        }

        // verify required parameter 'apiApplication' is not null or undefined
        if (apiApplication === null || apiApplication === undefined) {
            throw new Error('Required parameter apiApplication was null or undefined when calling _73fbde3b871d62621a0851e12ef3044c.');
        }

        // verify required parameter 'apiEnvironment' is not null or undefined
        if (apiEnvironment === null || apiEnvironment === undefined) {
            throw new Error('Required parameter apiEnvironment was null or undefined when calling _73fbde3b871d62621a0851e12ef3044c.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Update a variable
     * @param apiOrganisation The organisation ID
     * @param apiApplication The application ID
     * @param apiEnvironment The environment ID
     * @param apiVariable The variable key
     * @param d481164c455528711c302ff5e2b2bf5bRequest 
     */
    public async d481164c455528711c302ff5e2b2bf5b (apiOrganisation: string, apiApplication: string, apiEnvironment: string, apiVariable: string, d481164c455528711c302ff5e2b2bf5bRequest: D481164c455528711c302ff5e2b2bf5bRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/organisations/{api_organisation}/applications/{api_application}/environments/{api_environment}/variables/{api_variable}'
            .replace('{' + 'api_organisation' + '}', encodeURIComponent(String(apiOrganisation)))
            .replace('{' + 'api_application' + '}', encodeURIComponent(String(apiApplication)))
            .replace('{' + 'api_environment' + '}', encodeURIComponent(String(apiEnvironment)))
            .replace('{' + 'api_variable' + '}', encodeURIComponent(String(apiVariable)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'apiOrganisation' is not null or undefined
        if (apiOrganisation === null || apiOrganisation === undefined) {
            throw new Error('Required parameter apiOrganisation was null or undefined when calling d481164c455528711c302ff5e2b2bf5b.');
        }

        // verify required parameter 'apiApplication' is not null or undefined
        if (apiApplication === null || apiApplication === undefined) {
            throw new Error('Required parameter apiApplication was null or undefined when calling d481164c455528711c302ff5e2b2bf5b.');
        }

        // verify required parameter 'apiEnvironment' is not null or undefined
        if (apiEnvironment === null || apiEnvironment === undefined) {
            throw new Error('Required parameter apiEnvironment was null or undefined when calling d481164c455528711c302ff5e2b2bf5b.');
        }

        // verify required parameter 'apiVariable' is not null or undefined
        if (apiVariable === null || apiVariable === undefined) {
            throw new Error('Required parameter apiVariable was null or undefined when calling d481164c455528711c302ff5e2b2bf5b.');
        }

        // verify required parameter 'd481164c455528711c302ff5e2b2bf5bRequest' is not null or undefined
        if (d481164c455528711c302ff5e2b2bf5bRequest === null || d481164c455528711c302ff5e2b2bf5bRequest === undefined) {
            throw new Error('Required parameter d481164c455528711c302ff5e2b2bf5bRequest was null or undefined when calling d481164c455528711c302ff5e2b2bf5b.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'PUT',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(d481164c455528711c302ff5e2b2bf5bRequest, "D481164c455528711c302ff5e2b2bf5bRequest")
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
