name: Test SDK

on:
  push:
    branches: [ main, v3 ]
  pull_request:
    branches: [ main, v3 ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run smoke tests
      run: npm test
    
    - name: Verify package exports
      run: |
        node -e "const api = require('./dist/api.js'); \
          const apiCount = Object.keys(api).filter(k => k.endsWith('Api')).length; \
          console.log('✓ Exported', apiCount, 'API classes'); \
          if (apiCount < 20) throw new Error('Expected at least 20 APIs');"
    
    - name: Test example compilation
      run: |
        npm run build
        node dist/examples/basic-usage.js || echo "Example requires API credentials"
    
    - name: Check TypeScript definitions
      run: |
        test -f dist/api.d.ts || (echo "Missing TypeScript definitions" && exit 1)
        test -f dist/model/models.d.ts || echo "Warning: model definitions may be missing"

  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Clean install and build
      run: |
        npm ci
        npm run build
    
    - name: Package
      run: npm pack
    
    - name: Test package installation
      run: |
        PACKAGE_FILE=$(ls *.tgz)
        mkdir test-install
        cd test-install
        npm init -y
        npm install ../$PACKAGE_FILE
        node -e "const api = require('@quantcdn/quant-client'); \
          console.log('✓ Package installs and loads correctly'); \
          console.log('✓ Main export:', typeof api.ApplicationsApi);"
    
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: npm-package
        path: '*.tgz'
        retention-days: 7
